#
# Copyright (c) 2024 Alibaba Group Holding Limited. All Rights Reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation. Alibaba designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#

name: 'Build (riscv)'

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      extra-conf-options:
        required: false
        type: string
      make-target:
        required: false
        type: string
        default: 'product-bundles test-bundles'
      debug-levels:
        required: false
        type: string
        default: '[ "release" ]'
      gcc-major-version:
        required: false
        type: string
      gcc-package-suffix:
        required: false
        type: string
        default: ''
      apt-architecture:
        required: false
        type: string
      apt-extra-packages:
        required: false
        type: string
      configure-arguments:
        required: false
        type: string
      make-arguments:
        required: false
        type: string

jobs:
  build-linux:
    name: build
    runs-on: [self-hosted , X64]
    container:
      image: docker.io/alibabadragonwelljdk/centos7_gcc7_build_image:latest

    strategy:
      fail-fast: false
      matrix:
        debug-level: ${{ fromJSON(inputs.debug-levels) }}

    steps:
      - name: 'Checkout the JDK source'
        uses: actions/checkout@v2

      - name: 'Configure'
        run: >
          LD_LIBRARY_PATH=/opt/riscv_toolchain_linux/lib64
          PATH=/opt/riscv_toolchain_linux/bin:/usr/local/gcc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          bash configure
          --verbose
          --with-vendor-name=Alibaba
          --with-vendor-url=http://www.alibabagroup.com
          --with-vendor-bug-url='mailto:dragonwell_use@googlegroups.com'
          --with-vendor-vm-bug-url='mailto:dragonwell_use@googlegroups.com'
          --without-version-opt
          --without-version-pre
          --with-version-build=9
          --with-version-patch=14
          --with-boot-jdk=/usr/lib/jvm/jdk-10
          --with-native-debug-symbols=external
          --with-jvm-variants=server
          --disable-warnings-as-errors
          --openjdk-target=riscv64-unknown-linux-gnu
          --with-sysroot=/opt/fedora28_riscv_root
          ${{ inputs.extra-conf-options }} ${{ inputs.configure-arguments }} || (
          echo "Dumping config.log:" &&
          cat config.log &&
          exit 1)

      - name: 'Build'
        id: build
        uses: ./.github/actions/do-build
        with:
          make-target: '${{ inputs.make-target }} ${{ inputs.make-arguments }}'
          platform: ${{ inputs.platform }}
          debug-suffix: '${{ matrix.suffix }}'

      - name: 'Upload bundles'
        uses: ./.github/actions/upload-bundles
        with:
          platform: ${{ inputs.platform }}
          debug-suffix: '${{ matrix.suffix }}'
