#
# Copyright (c) 2019 Alibaba Group Holding Limited. All Rights Reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation. Alibaba designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#

name: Dragonwell_11_build_test

on: [pull_request]

jobs:
  check_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dragonwell-releng/check_commit_action@master

  build_release_amd64_jdk:
    runs-on: ubuntu-latest
    container:
      image: docker.io/alibabadragonwelljdk/build_jdk:11-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile release mode on amd64
        run: |
          chmod 755 configure
          bash make.sh release

      - name: Sanity test
        run: |
          TEST_JDK_HOME=build/linux-x86_64-normal-server-release/images/jdk
          ${TEST_JDK_HOME}/bin/java -version

  build_release_arm64_jdk:
    runs-on: [self-hosted , ARM64]
    container:
      image: docker.io/alibabadragonwelljdk/build_jdk:11-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile release mode on arm64
        run: |
          chmod 755 configure
          bash make.sh release

      - name: Sanity test
        run: |
          TEST_JDK_HOME=build/linux-aarch64-normal-server-release/images/jdk
          ${TEST_JDK_HOME}/bin/java -version

  build_fastdebug_amd64_jdk:
    runs-on: ubuntu-latest
    container:
      image: docker.io/alibabadragonwelljdk/build_jdk:11-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile slowdebug mode
        run: |
          chmod 755 configure
          bash make.sh fastdebug

      - name: Sanity test
        run: |
          TEST_JDK_HOME=build/linux-x86_64-normal-server-fastdebug/images/jdk
          ${TEST_JDK_HOME}/bin/java -version

  build_slowdebug_amd64_jdk:
    runs-on: ubuntu-latest
    container:
      image: docker.io/alibabadragonwelljdk/build_jdk:11-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile slowdebug mode
        run: |
          chmod 755 configure
          bash make.sh debug

      - name: Sanity test
        run: |
          TEST_JDK_HOME=build/linux-x86_64-normal-server-slowdebug/images/jdk
          ${TEST_JDK_HOME}/bin/java -version

  build_release_riscv_jdk:
    runs-on: ubuntu-latest
    container:
      image: docker.io/alibabadragonwelljdk/centos7_gcc7_build_image:latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile release mode riscv jdk
        run: |
          chmod 755 configure
          LD_LIBRARY_PATH=/opt/riscv_toolchain_linux/lib64 \
          PATH=/opt/riscv_toolchain_linux/bin:/usr/local/gcc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
          bash configure --verbose --with-vendor-name=Alibaba --with-vendor-url=http://www.alibabagroup.com --with-vendor-bug-url='mailto:dragonwell_use@googlegroups.com' --with-vendor-vm-bug-url='mailto:dragonwell_use@googlegroups.com' --with-vendor-name=Alibaba --with-vendor-url=http://www.alibabagroup.com --with-vendor-bug-url='mailto:dragonwell_use@googlegroups.com' --with-vendor-vm-bug-url='mailto:dragonwell_use@googlegroups.com' --without-version-opt --without-version-pre --with-version-build=9 --with-version-patch=14 --with-boot-jdk=/usr/lib/jvm/jdk-10 --with-debug-level=release --with-native-debug-symbols=external --with-jvm-variants=server --disable-warnings-as-errors --openjdk-target=riscv64-unknown-linux-gnu --with-sysroot=/opt/fedora28_riscv_root -with-boot-jdk=/usr/lib/jvm/jdk-10 --openjdk-target=riscv64-unknown-linux-gnu --with-sysroot=/opt/fedora28_riscv_root
          make images
